# Generated by Django 5.2.1 on 2026-09-26 19:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la catégorie')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('description', models.TextField(blank=True, verbose_name='Description SEO')),
            ],
            options={
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False, verbose_name="Lu par l'équipe")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('phone', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('wilaya', models.CharField(max_length=100, verbose_name='Wilaya')),
                ('commune', models.CharField(max_length=100, verbose_name='Commune')),
                ('address', models.TextField(verbose_name='Adresse exacte')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant Total')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais de livraison')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('shipped', 'Expédiée'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='Statut de la commande')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Payée')),
                ('tracking_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Code de suivi (ex. Yalidine)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkinType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Type de peau')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix initial (DZD)')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix réduit (DZD)')),
                ('stock', models.PositiveIntegerField(default=10, verbose_name='Quantité en stock')),
                ('sales_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de ventes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Disponible à la vente')),
                ('is_featured', models.BooleanField(default=False, verbose_name="Mettre en avant sur l'accueil")),
                ('main_image', models.ImageField(upload_to='products/main/', verbose_name='Image principale')),
                ('short_description', models.TextField(blank=True, verbose_name='Accroche courte')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('formula', models.TextField(blank=True, verbose_name='La Formule')),
                ('ingredients', models.TextField(verbose_name='Ingrédients (INCI)')),
                ('benefits', models.TextField(verbose_name='Bénéfices')),
                ('usage_instructions', models.TextField(verbose_name="Conseils d'utilisation")),
                ('active_ingredients_title', models.CharField(blank=True, max_length=200, verbose_name='Titre Principes Actifs')),
                ('active_ingredients', models.TextField(blank=True, verbose_name='Détails Principes Actifs')),
                ('problem_repair_method', models.TextField(blank=True, verbose_name='Méthode de réparation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category', verbose_name='Catégorie')),
                ('skin_types', models.ManyToManyField(related_name='products', to='store.skintype', verbose_name='Types de peau recommandés')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='BeforeAfter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Résultats Avant / Après', max_length=200)),
                ('before_image', models.ImageField(upload_to='before_after/')),
                ('after_image', models.ImageField(upload_to='before_after/')),
                ('short_description', models.CharField(help_text="Ex: Résultats constatés après 3 semaines d'utilisation quotidienne.", max_length=255)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='before_after', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/secondary/')),
                ('alt_text', models.CharField(blank=True, help_text='Texte alternatif pour le référencement SEO', max_length=150)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_images', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('video_url', models.URLField(blank=True, help_text='Lien TikTok, Instagram Reel ou YouTube', null=True)),
                ('thumbnail', models.ImageField(upload_to='videos/thumbnails/', verbose_name='Miniature')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='Nom du client')),
                ('rating', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(verbose_name='Avis')),
                ('image', models.ImageField(blank=True, null=True, upload_to='reviews/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='reviews/videos/')),
                ('is_approved', models.BooleanField(default=False, verbose_name="Approuvé par l'admin")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('banner_image', models.ImageField(upload_to='offers/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_offers', to='store.product')),
            ],
        ),
    ]
