# Generated by Django 5.2.1 on 2026-09-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Type d'utilisation / Besoins")),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='beforeafter',
            name='after_image',
            field=models.ImageField(upload_to='before_after/', verbose_name='Photo Après'),
        ),
        migrations.AlterField(
            model_name='beforeafter',
            name='before_image',
            field=models.ImageField(upload_to='before_after/', verbose_name='Photo Avant'),
        ),
        migrations.AlterField(
            model_name='product',
            name='benefits',
            field=models.TextField(verbose_name='Bénéfices du produit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='problem_repair_method',
            field=models.TextField(blank=True, verbose_name='Méthode de réparation du problème'),
        ),
        migrations.AlterField(
            model_name='product',
            name='usage_instructions',
            field=models.TextField(verbose_name="Conseils / Mode d'utilisation"),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Texte alternatif SEO', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='usage_types',
            field=models.ManyToManyField(related_name='products', to='store.usagetype', verbose_name="Types d'utilisation / Besoins"),
        ),
    ]
