# Generated by Django 5.2.1 on 2026-09-26 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_usagetype_alter_beforeafter_after_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='active_ingredients',
        ),
        migrations.RemoveField(
            model_name='product',
            name='active_ingredients_title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='problem_repair_method',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='benefits',
            field=models.TextField(blank=True, verbose_name='Bénéfices'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix promo (DZD)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='formula',
            field=models.TextField(blank=True, verbose_name='Formule / Composition globale'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, verbose_name='Liste INCI des ingrédients'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Mettre en avant'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(upload_to='products/', verbose_name='Image principale'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (DZD)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Courte description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='skin_types',
            field=models.ManyToManyField(blank=True, related_name='products', to='store.skintype', verbose_name='Types de peau'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité en stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='usage_instructions',
            field=models.TextField(blank=True, verbose_name="Conseils d'utilisation"),
        ),
        migrations.AlterField(
            model_name='product',
            name='usage_types',
            field=models.ManyToManyField(blank=True, related_name='products', to='store.usagetype', verbose_name="Types d'utilisation"),
        ),
        migrations.AlterField(
            model_name='skintype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Type de peau'),
        ),
        migrations.AlterField(
            model_name='skintype',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='usagetype',
            name='name',
            field=models.CharField(max_length=100, verbose_name="Type d'utilisation"),
        ),
        migrations.AlterField(
            model_name='usagetype',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.CreateModel(
            name='ProductActiveIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du principe actif')),
                ('repair_method', models.TextField(verbose_name='Méthode de réparation / Action')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_ingredients_list', to='store.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Principe Actif',
                'verbose_name_plural': 'Principes Actifs',
            },
        ),
    ]
