# Generated by Django 5.2.1 on 2026-09-27 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cod', 'Paiement à la livraison'), ('edahabia', 'Carte Edahabia'), ('cib', 'Carte CIB'), ('baridimob', 'Virement BaridiMob')], default='cod', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Montant payé en DZD', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payée'), ('failed', 'Échouée'), ('refunded', 'Remboursée')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, db_index=True, help_text='ID de transaction de la passerelle (ex: Chargily/SATIM)', max_length=255, null=True)),
                ('raw_response', models.JSONField(blank=True, help_text='Réponse JSON brute du Webhook/Passerelle', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='store.order')),
            ],
        ),
    ]
