# Generated by Django 5.2.1 on 2026-09-27 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_wishlist_wishlistitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, help_text='Pourcentage de réduction (ex: 10.00 pour 10%)', max_digits=5)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Montant minimum en DZD', max_digits=10)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text="Nombre max d'utilisations totales", null=True)),
                ('used_count', models.PositiveIntegerField(default=0, help_text="Nombre d'utilisations actuelles")),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Code Promo',
                'verbose_name_plural': 'Codes Promo',
            },
        ),
        migrations.AlterModelOptions(
            name='beforeafter',
            options={'verbose_name': 'Avant / Après', 'verbose_name_plural': 'Avant / Après'},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Panier', 'verbose_name_plural': 'Paniers'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Article du panier', 'verbose_name_plural': 'Articles du panier'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'Message de contact', 'verbose_name_plural': 'Messages de contact'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Article de commande', 'verbose_name_plural': 'Articles de commande'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Paiement', 'verbose_name_plural': 'Paiements'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Image secondaire', 'verbose_name_plural': 'Images secondaires'},
        ),
        migrations.AlterModelOptions(
            name='productvideo',
            options={'verbose_name': 'Vidéo produit', 'verbose_name_plural': 'Vidéos produits'},
        ),
        migrations.AlterModelOptions(
            name='skintype',
            options={'verbose_name': 'Type de peau', 'verbose_name_plural': 'Types de peau'},
        ),
        migrations.AlterModelOptions(
            name='specialoffer',
            options={'verbose_name': 'Offre spéciale', 'verbose_name_plural': 'Offres spéciales'},
        ),
        migrations.AlterModelOptions(
            name='usagetype',
            options={'verbose_name': "Type d'utilisation", 'verbose_name_plural': "Types d'utilisation"},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'Liste de souhaits', 'verbose_name_plural': 'Listes de souhaits'},
        ),
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Article de wishlist', 'verbose_name_plural': 'Articles de wishlist'},
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant réduction (DZD)'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Paiement à la livraison (COD)'), ('baridimob', 'BaridiMob'), ('ccp', 'Virement CCP')], default='cod', max_length=20, verbose_name='Mode de paiement'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais de livraison (DZD)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('shipped', 'Expédiée'), ('delivered', 'Livrée'), ('returned', 'Retournée'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='Statut de la commande'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant des produits (DZD)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('wilaya', models.CharField(max_length=100)),
                ('commune', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adresses',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.coupon', verbose_name='Code Promo'),
        ),
    ]
