# Generated by Django 5.2.1 on 2026-09-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_coupon_alter_beforeafter_options_alter_cart_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant des produits (DZD)'),
        ),
    ]
