# Generated by Django 5.2.1 on 2026-09-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_cartitem_quantity_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvideo',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Vidéo produit', 'verbose_name_plural': 'Vidéos produits'},
        ),
        migrations.AddField(
            model_name='productvideo',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='1 pour la première position, 2 pour la deuxième, etc.', verbose_name="Ordre d'affichage (Position)"),
        ),
    ]
