# Generated by Django 5.2.1 on 2026-09-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_productvideo_options_productvideo_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialoffer',
            name='product',
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='products',
            field=models.ManyToManyField(related_name='special_offers', to='store.product', verbose_name='Produits inclus'),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='special_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix spécial du pack (DZD)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='offers/', verbose_name='Bannière (optionnelle)'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sous-titre'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='title',
            field=models.CharField(max_length=150, verbose_name="Titre de l'offre"),
        ),
    ]
