# Generated by Django 5.2.1 on 2026-09-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_specialoffer_product_specialoffer_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='videos/thumbnails/', verbose_name='Miniature'),
        ),
    ]
