# Generated by Django 5.2.1 on 2026-09-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_productvideo_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='productactiveingredient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ingredients/', verbose_name="Image de l'ingrédient"),
        ),
    ]
