# Generated by Django 5.2.1 on 2026-09-30 12:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_productactiveingredient_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('home_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Prix Domicile')),
                ('desk_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Prix Stop Desk')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Wilaya & Tarif',
                'verbose_name_plural': 'Wilayas & Tarifs',
                'ordering': ['code'],
            },
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
