# Generated by Django 5.2.1 on 2026-10-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_product_hover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialoffer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='offers/', verbose_name="Image de l'offre"),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='offers/banners/', verbose_name='Bannière (optionnelle)'),
        ),
    ]
